# Generated by Django 5.0.6 on 2024-08-05 09:27

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=1, max_length=500, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='no_image.jpg', force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='catigory_images/', verbose_name='фото категории'),
        ),
    ]
