# Generated by Django 5.0.6 on 2024-08-02 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255, verbose_name='Характиристика товары')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feature', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характиристика торава',
                'verbose_name_plural': 'Характиристики товаров',
            },
        ),
    ]
