# Generated by Django 5.0.6 on 2024-08-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
    ]
