# Generated by Django 5.0.6 on 2024-08-06 09:14

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_cart_cartitem_color_cartitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', 'WHITE'), ('BLACK', 'BLACK'), ('GRAY', 'GRAY'), ('BROWN', 'BROWN')], max_length=255, null=True, verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='Фото изделий'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Цена сейчас'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество продукта'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=100, null=True, verbose_name='Размер товара'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Итоговая цена товаров'),
        ),
    ]
