# Generated by Django 5.0.6 on 2024-08-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='old_price',
        ),
        migrations.AddField(
            model_name='slider',
            name='main_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='price',
            field=models.IntegerField(default=1, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
