# Generated by Django 5.0.6 on 2024-08-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_setting_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='mobile_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип'),
        ),
    ]
