# Generated by Django 5.0.6 on 2024-08-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('home', models.CharField(max_length=255, verbose_name='Дом')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефонный номер')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Биллинг',
                'verbose_name_plural': 'Биллинги',
            },
        ),
    ]
