# Generated by Django 5.0.6 on 2024-08-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_remove_orderitem_order_remove_orderitem_product_and_more'),
        ('products', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_products', to='products.product', verbose_name='Товар'),
        ),
    ]
