# Generated by Django 5.0.6 on 2024-08-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_alter_billingproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingproduct',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
