# Generated by Django 5.0.6 on 2024-08-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0006_alter_billingproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingproduct',
            name='billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.billings'),
        ),
    ]
